/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-07-19 18:07:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class body_002dchatting_002dframe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar textarea = document.getElementById(\"chat\");\r\n");
      out.write("\tvar webSocket = new WebSocket('ws://localhost:8070/Tiramisu/broadcasting');\r\n");
      out.write("\tvar inputMessage = document.getElementById('dialogInput');\r\n");
      out.write("\tvar nickname = null;\r\n");
      out.write("\tvar time = null;\r\n");
      out.write("\tvar content = null;\r\n");
      out.write("\twebSocket.onerror = function(event) {\r\n");
      out.write("\t\tonError(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onopen = function(event) {\r\n");
      out.write("\t\tonOpen(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onmessage = function(event) {\r\n");
      out.write("\t\tonMessage(event)\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction onMessage(event) {\r\n");
      out.write("\t\tvar recMessage = event.data;\r\n");
      out.write("\t\tconsole.log(recMessage);\r\n");
      out.write("\t\trecMessage = recMessage.split('`');\r\n");
      out.write("\t\tconsole.log(recMessage[0]);\r\n");
      out.write("\t\tconsole.log(recMessage[1]);\r\n");
      out.write("\t\tconsole.log(recMessage[2]);\r\n");
      out.write("\t\ttextarea.innerHTML += '<li class=\"left clearfix\"><span class=\"chat-img pull-left\">\\\r\n");
      out.write("\t\t\t<img src=\"images/tirami.PNG\" alt=\"User Avatar\">\\\r\n");
      out.write("\t\t</span>\\\r\n");
      out.write("\t\t\t<div class=\"chat-body clearfix\">\\\r\n");
      out.write("\t\t\t\t<div class=\"header\">\\\r\n");
      out.write("\t\t\t\t\t<strong class=\"primary-font\">'+ recMessage[0] +'</strong> <small\\\r\n");
      out.write("\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>'+\r\n");
      out.write("\t\t\t\t\t\t+ recMessage[1] +'</small>\\\r\n");
      out.write("\t\t\t\t</div>\\\r\n");
      out.write("\t\t\t\t<p>'+ recMessage[2] +'</p>\\\r\n");
      out.write("\t\t\t</div></li>';\r\n");
      out.write("\t\t//textarea.value += \"상대 : \" + event.data + \"\\n\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onOpen(event) {\r\n");
      out.write("\t\tconsole.log(\"연결 성공\\n\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onError(event) {\r\n");
      out.write("\t\talert(event.data);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction send() {\r\n");
      out.write("\t\tcontent = document.getElementById(\"dialogInput\").value;\r\n");
      out.write("\t\ttime = new Date();\r\n");
      out.write("\t\tnickname = \"");
      out.print(session.getAttribute("nickname"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t\ttextarea.innerHTML += '<li class=\"right clearfix\"><span class=\"chat-img pull-right\">\\\r\n");
      out.write("\t\t\t<img src=\"images/me.jpg\" alt=\"User Avatar\">\\\r\n");
      out.write("\t\t</span>\\\r\n");
      out.write("\t\t\t<div class=\"chat-body clearfix\">\\\r\n");
      out.write("\t\t\t\t<div class=\"header\">\\\r\n");
      out.write("\t\t\t\t\t<strong class=\"primary-font\">'+ nickname +'</strong> <small\\\r\n");
      out.write("\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>'+\r\n");
      out.write("\t\t\t\t\t\t+ time +'</small>\\\r\n");
      out.write("\t\t\t\t</div>\\\r\n");
      out.write("\t\t\t\t<p>'+ content +'</p>\\\r\n");
      out.write("\t\t\t</div></li>';\r\n");
      out.write("\t\tsendMessage = nickname+\"`\"+time+\"`\"+content;\r\n");
      out.write("\t\twebSocket.send(sendMessage);\r\n");
      out.write("\t\tinputMessage.value = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t/*Debug function*/\r\n");
      out.write("\tfunction dialogSubmit(){\r\n");
      out.write("\t\tcontent = document.getElementById(\"dialogInput\").value;\r\n");
      out.write("\t\ttime = new Date();\r\n");
      out.write("\t\tnickname = \"");
      out.print(session.getAttribute("nickname"));
      out.write("\";\r\n");
      out.write("\t\t/*document.writeln(content);\r\n");
      out.write("\t\tdocument.writeln(time);\r\n");
      out.write("\t\tdocument.writeln(nickname);*/\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/chatting.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<div class=\"container bootstrap snippet\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!--=========================================================-->\r\n");
      out.write("\t\t<!-- selected chat -->\r\n");
      out.write("\t\t<div class=\"col-md-8 bg-white \">\r\n");
      out.write("\t\t\t<div style=\"overflow-y: scroll; height: 700px;\">\r\n");
      out.write("\t\t\t\t<div class=\"chat-message\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"chat\" id=\"chat\">\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/chatting-left-clearfix.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("chatNickname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("이형건", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("chatTime", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("2017-07-18 AM 05:45", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("chatContent", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("오늘 11시까지인데 밥언제 먹나요...:(", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/chatting-right-clearfix.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("chatNickname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("변다영", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("chatTime", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("2017-07-18 AM 05:46", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("chatContent", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("지금 당장 먹어도 시원찮습니다", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"left clearfix\"><span class=\"chat-img pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/tirami.PNG\" alt=\"User Avatar\">\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"chat-body clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"primary-font\">이성민</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2017-07-18 AM 05:47</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>나도 머글랭</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"right clearfix\"><span class=\"chat-img pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/me.jpg\" alt=\"User Avatar\">\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"chat-body clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2017-07-18 AM 05:49</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>오빠도 먹죠</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"left clearfix\"><span class=\"chat-img pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/tirami.PNG\" alt=\"User Avatar\">\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"chat-body clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"primary-font\">김태정</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>나는 아무거나 괜찮아요.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"right clearfix\"><span class=\"chat-img pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/me.jpg\" alt=\"User Avatar\">\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"chat-body clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>그 놈의 아무거나</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"right clearfix\"><span class=\"chat-img pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/me.jpg\" alt=\"User Avatar\">\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"chat-body clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2017-07-18 AM 05:51</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>아악!</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chat-box bg-white\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control border no-shadow no-rounded\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Type your message here\" id=\"dialogInput\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-success no-rounded\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"send()\">Send</button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /input-group -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--오른쪽 면 -->\r\n");
      out.write("\t\t<div class=\"col-md-4 bg-white \">\r\n");
      out.write("\t<div style=\"overflow-y: scroll; height: 700px;\">\r\n");
      out.write("\t\t<div class=\"chat-message\">\r\n");
      out.write("\t\t\t<ul class=\"chat\">\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\"><span class=\"chat-img pull-left\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/tirami.PNG\">\r\n");
      out.write("\t\t\t\t</span> <b class=\"primary-font\" style=\"font-size: 20px; color: #53270E\">&nbsp;&nbsp;변다영님의\r\n");
      out.write("\t\t\t\t\t\t과거 대화</b></li>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>보쌈은 동맥경화증, 고혈압 등의 성인병을 막는 효능을 하기 때문에 저는 회식을 갈비로 하는 것에 반대합니다\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>맥북은 에어보다 프로죠.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>저희 스터디 어떻게 할까요?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>오늘 점심은 KFC입니다. KFC 할아버지가 세상에서 제일 좋아</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>web.xml도 안보고 삽질을 하다니! 나는 바보다!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>배고프다</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>스크롤바 성공</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"left clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body clearfix\" style=\"margin-left: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"primary-font\">변다영</strong> <small\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-right text-muted\"><i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t2017-07-18 AM 05:50</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>초코칩 쿠키 굳</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

	//This scritp was occured error.

      out.write("\r\n");
      out.write("<!--  <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
