/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-07-21 01:26:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utillity.Tool;
import java.util.ArrayList;
import work.model.service.TeamService;
import work.model.dto.Team;

public final class search_002dinner_002dframe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utillity.Tool");
    _jspx_imports_classes.add("work.model.dto.Team");
    _jspx_imports_classes.add("work.model.service.TeamService");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String keyword= request.getParameter("keyword");
	TeamService service = TeamService.getInstance();
	ArrayList<Team> searchTeamName = service.getKeywordTeamName(keyword);
	ArrayList<Team> searchTeamSubject = service.getKeywordTeamSubject(keyword);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<script>\r\n");
      out.write("function joinTeam(tn){\r\n");
      out.write("\tlocation.href=\"TeamController?action=joinTeam&tn=\"+tn;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("<!--js-->\r\n");
      out.write("<script src=\"js/jquery-2.1.1.min.js\"></script> \r\n");
      out.write("<!--icons-css-->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!--Google Fonts-->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Work+Sans:400,500,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!--button css-->\r\n");
      out.write("<link href=\"css/demo-page.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"css/hover.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<!--//but-->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Work+Sans:400,500,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!--//skycons-icons-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-12 \">\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissable\" style=\"margin:15px\"><h4><b>'");
      out.print(keyword );
      out.write("'</b>에 대한 검색 결과입니다.</h4> </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"col-md-12 \">\r\n");
      out.write("<a href=\"#\" class=\"hvr-icon-grow\">전체</a>\r\n");
      out.write("<a href=\"#\" class=\"hvr-icon-pulse-shrink\">팀 이름으로 검색</a>\r\n");
      out.write("<a href=\"#\" class=\"hvr-icon-rotate\">주제로 검색</a>\r\n");
      out.write("</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 팀으로 검색 -->\r\n");
      out.write("<div class=\"btn-effcts panel-widget col-sm-8\" style=\"margin:30px\">\r\n");
      out.write(" <div class=\"button-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h4 style=\"color:#2E2D23\"> Search by <b>Team Name</b></h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
 for(Team t : searchTeamName){
      out.write("\r\n");
      out.write(" <div class=\"col-md-8 profile_details\" style=\"float:left; padding:20px; min-width:800px\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown profile_details_drop\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile_img\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"prfil-img\"><img src=\"images/Tiramisu.png\" alt=\"\" style=\"width: 50px; height: 50px;\"> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p style=\"color:#53270E\">");
      out.print( t.getTeamName() );
      out.write("<button type=\"button\" class=\"btn btn-xs btn-warning\"  style=\"width: 50px ;margin:2px 5px;\" onclick=\"joinTeam('");
      out.print(t.getTeamName() );
      out.write("')\">가입</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>");
      out.print(t.getSubject() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"hvr-icon-wobble-horizontal\" style=\"float:right; background-color:#ECCF97; color:#53270E; border:solid 1px #53270E\" >팀 더 보기</a>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 주제로 검색 -->\r\n");
      out.write("<div class=\"btn-effcts panel-widget col-sm-8\" style=\"margin:30px\">\r\n");
      out.write(" <div class=\"button-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h4 style=\"color:#2E2D23\"> Search by <b>Subject Name</b></h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
 for(Team t : searchTeamSubject){
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"col-md-8 profile_details\" style=\"float:left; padding:20px; min-width:800px\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown profile_details_drop\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile_img\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"prfil-img\"><img src=\"images/Tiramisu.png\" alt=\"\" style=\"width: 50px; height: 50px;\"> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p style=\"color:#53270E\">");
      out.print( t.getTeamName() );
      out.write("<button type=\"button\" class=\"btn btn-xs btn-warning\"  style=\"margin:2px 5px;\" onclick=\"joinTeam('");
      out.print(t.getTeamName() );
      out.write("')\">가입</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>");
      out.print(t.getSubject() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"hvr-icon-wobble-horizontal\" style=\"float:right; background-color:#ECCF97; color:#53270E; border:solid 1px #53270E\" >팀 더 보기</a>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
